project:
  type: book
  output-dir: _book
  post-render: quarto render --profile slides

book:
  reader-mode: false
  downloads: [pdf]
  page-navigation: true
  chapters:
    - index.qmd
    # - Week1/age-guessing.qmd
    # - part: Week2/index.qmd
    #   chapters:
    #     - Week2/live-slides.qmd
    - part: Week3/index-slides.qmd
      chapters:
        - Week3/prob-01-intro.qmd
        - Week3/prob-02-rules.qmd
        - Week3/prob-03-empirical.qmd
        - Week3/prob-04-conditional.qmd
        - Week3/prob-05-bayes.qmd
        - Week3/prob-06-distributions.qmd
        - Week3/prob-07-sampling-slides.qmd

execute:
  echo: true
  freeze: auto
  warning: false
  message: false
  cache: true

format:
  html:
    number-sections: false
    theme: cosmo
    code-fold: true
  pdf:
    documentclass: scrbook
    execute:
      cache: true

  # Tufte style theming

  # html:
  #   code-fold: true
  #   page-layout: full
  #   reference-location: margin
  #   title-block-style: none
  #   css: _extensions/fredguth/tufte/styles.css
  #   number-sections: false
  #   linkcolor: Maroon
  #   backgroundcolor: FloralWhite
  #   sidebarbackgroundcolor: FloralWhite
  #   mainfont: "heuristica"
  #   toc-title: "Contents"
  #   code-annotations: hover
  #   default-image-extension: svg
  #   filters:
  #     - _extensions/fredguth/tufte-inspired/citing-html.lua
  # pdf:
  #   reference-location: margin
  #   citation-location: margin
  #   fig-cap-location: bottom
  #   documentclass: tufte-book
  #   classoption: [sfsidenotes]
  #   number-sections: false
  #   format-resources:
  #     - _extensions/fredguth/tufte/tufte-book.cls
  #     - _extensions/fredguth/tufte/tufte-common.def
  #     - _extensions/fredguth/tufte/tufte.bst
  #   template-partials: # replaces
  #     - "_extensions/fredguth/tufte/partials/title.tex"
  #     - "_extensions/fredguth/tufte/partials/before-body.tex"
  #   include-in-header: #adds
  #     - "_extensions/fredguth/tufte/partials/in-header.tex"
  #     - "_extensions/fredguth/tufte/partials/definitions.tex"
  #   include-after-body: #adds
  #     - "_extensions/fredguth/tufte/partials/after-body.tex"
  #   toc-depth: 2
  #   toc-title: "Contents"
  #   indent: 0px
  #   # biblio-style: dinat
  #   cite-method: natbib
  #   # mainfont: "Minion Pro"
  #   mainfont: "ETbb"
  #   sansfont: "TeX Gyre Heros"
  #   sansfontoptions: "Scale=MatchUppercase"
  #   default-image-extension: pdf
