project:
  output-dir: _book/_slides
  render:
    - "Week2/live-slides.qmd"

format:
  live-revealjs:
    execute:
      edit: true
    theme: [default, clean.scss]
    slide-number: true
    show-slide-number: all
    progress: true
    transition: slide
    background-transition: fade
    preview-links: auto
    width: 1247
    height: 810
    scrollable: true
  clean-typst: default

filters:
  - live
  - fontawesome
