project:
  output-dir: _book/_slides
  render:
    - "Week4/*.qmd"
    - "*slides.qmd"
    - "!*live-slides.qmd"
    - "!*.Rmd"
    - "!old-*.qmd"
    - "!old*/"
  # post-render: quarto render --profile live-slides

format:
  clean-revealjs:
    execute:
      echo: false
      freeze: auto
    r-fit-text: true
    incremental: true
    theme: [default, clean.scss]
    slide-number: true
    show-slide-number: all
    progress: true
    transition: slide
    background-transition: fade
    preview-links: auto
    width: 1247
    height: 810
    scrollable: true
  clean-typst: default

filters:
  - live
  - fontawesome
